---
- name: stop firewalld
  service: 
    name: firewalld
    state: stopped
    enabled: no
- name: close selinux 
  shell: setenforce 0 || /usr/bin/true
- name: disable selinux
  replace:
    path: /etc/selinux/config
    regexp: '^(SELINUX=).*'
    replace: '\1disabled'

